"""
Django settings for school_sms project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config 
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-fallback-key-for-build-purposes')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = config('DEBUG', default=False, cast=bool)

# Allowed hosts
if config('DEBUG', default=False, cast=bool):
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = config(
        'ALLOWED_HOSTS',
        default='127.0.0.1,localhost,10.103.148.197'
    ).split(',')

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://10.88.146.65'
).split(',')



CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG


CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_FAILURE_VIEW = "mpay.views.csrf_failure"


# Application definition

INSTALLED_APPS = [
    'daphne',
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third-party apps
    'channels',
    'crispy_forms',
    'crispy_bootstrap5',
    'storages',
    

    # Local Apps (The four pillars of this project)
    'exams.apps.ExamsConfig',                         
    'accounts.apps.AccountsConfig',
    'mpay.apps.MpayConfig',
    'pickup.apps.PickupConfig',
    'payroll.apps.PayrollConfig',
    'loans.apps.LoansConfig',
    'leaves.apps.LeavesConfig',
    'dashboards.apps.DashboardsConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'accounts.middleware.IdleTimeoutMiddleware',  
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE += [
    'accounts.middleware.ProfileCompletionMiddleware',
]


ROOT_URLCONF = 'school_sms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'school_sms.context_processors.school_context',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


ASGI_APPLICATION = 'school_sms.asgi.application'
WSGI_APPLICATION = 'school_sms.wsgi.application'

# Channels Configuration
REDIS_URL = config("REDIS_URL", default="redis://localhost:6379/0")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            "capacity": 1500,
            "expiry": 10,
        },
    }
}



# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='muflihun'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='idrees'),
        'HOST': config('DB_HOST', default='db'),
        'PORT': config('DB_PORT', default='5432'),
    }
} 

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



import os
import logging
from logging.handlers import RotatingFileHandler


LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} | {levelname} | {name} | {module} | {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'system.log'),
            'maxBytes': 5*1024*1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # Central logger for all apps
        'project': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Specific apps (optional)
        'mpay': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'exams': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'pickups': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True   


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Login URLs
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "acccounts:dashboard_redirect"
LOGOUT_REDIRECT_URL = "accounts:login"


# SESSION_COOKIE_SECURE = False   # dev only
# CSRF_COOKIE_SECURE = False      # dev only

# # settings.py
# SESSION_COOKIE_AGE = 1200 # 20 minutes
# SESSION_SAVE_EVERY_REQUEST = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Lagos'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Use WhiteNoise only if not behind Nginx or for extra safety
if not config('USE_NGINX', default=False, cast=bool):
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

## School config (dynamic)
SCHOOL_NAME = config("SCHOOL_NAME", "Muflihun High School")
SCHOOL_ADDRESS = config("SCHOOL_ADDRESS", "")
SCHOOL_LOGO_PATH = os.path.join(BASE_DIR, "static", "images", "school_logo.png")
SCHOOL_SLOGAN = config("SCHOOL_SLOGAN", "")
SCHOOL_ECOMMERCE = config("SCHOOL_ECOMMERCE", "")
SCHOOL_PHONE = config("SCHOOL_PHONE", "")
SCHOOL_EMAIL = config("SCHOOL_EMAIL", "muflihunhighschool@gmail.com")
SCHOOL_APP_NAME = config("SCHOOL_APP_NAME", "")
SCHOOL_FACEBOOK_URL = config("SCHOOL_FACEBOOK_URL", "#")
SCHOOL_TWITTER_URL = config("SCHOOL_TWITTER_URL", "#")
SCHOOL_INSTAGRAM_URL = config("SCHOOL_INSTAGRAM_URL", "#")
SCHOOL_YOUTUBE_URL = config("SCHOOL_YOUTUBE_URL", "#")

PORTAL_DOMAIN = config("PORTAL_DOMAIN", "")
SITE_NAME = config("SITE_NAME", "")
CURRENCY = config('CURRENCY', default='NGN')
CURRENCY_SYMBOL = config('CURRENCY_SYMBOL', default='₦')
RECEIPT_WATERMARK = "PAID"


# Custom User Model (Best Practice)
AUTH_USER_MODEL = 'accounts.User' 

# Tailwind Config (Use these values for django-tailwind setup)
TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

# Paystack Config (Add this new section)
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY', default='pk_test_placeholder')
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY', default='sk_test_placeholder')
PAYSTACK_BASE_URL = config('PAYSTACK_BASE_URL', default='https://api.paystack.co')
PAYSTACK_WEBHOOK = config(
    'PAYSTACK_WEBHOOK_SECRET', default='https://newsiest-interlineally-guy.ngrok-free.dev/mpay/paystack/webhook/')
PAYSTACK_CALLBACK_URL = config(
    "PAYSTACK_CALLBACK_URL",
    default="https://newsiest-interlineally-guy.ngrok-free.dev/mpay/paystack/callback/"
)


# AWS S3 CONFIGURATION
USE_S3 = config('USE_S3', default=False, cast=bool)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default=None)
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default=None)
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default=None)
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='eu-west-2')
AWS_DEFAULT_ACL = config('AWS_DEFAULT_ACL', default='public-read')
AWS_BACKUP_FOLDER = 'backups'

if USE_S3:
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    
    # S3 Storage classes
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }
    
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
else:
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    # Use WhiteNoise only if not behind Nginx or for extra safety
    if not config('USE_NGINX', default=False, cast=bool):
        STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# -----------------------------------------


# Email
EMAIL_BACKEND='django.core.mail.backends.console.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER='your-email@gmail.com'

# Telegram Bot Config
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_CHAT_ID = config('TELEGRAM_CHAT_ID', default='')
EMAIL_HOST_PASSWORD='your-app-password'
DEFAULT_FROM_EMAIL='noreply@schoolcommerce.com'

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Backup
BACKUP_ENCRYPTION_KEY = config("BACKUP_ENCRYPTION_KEY", default='placeholder-encryption-key')
BACKUP_RETENTION_DAYS = 30
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Web Push (VAPID)
VAPID_PUBLIC_KEY = config('VAPID_PUBLIC_KEY', default='')
VAPID_PRIVATE_KEY = config('VAPID_PRIVATE_KEY', default='').replace('\\n', '\n')
VAPID_ADMIN_EMAIL = config('VAPID_ADMIN_EMAIL', default=SCHOOL_EMAIL)

# Celery Configuration Options

CELERY_BEAT_SCHEDULE = {
    'cleanup_pickups_every_hour': {
        'task': 'pickups.tasks.cleanup_expired_pickups',
        'schedule': 3600.0,
    },
    'backup_project_daily': {
        'task': 'school_sms.task.backup_project_data',
        'schedule': 24*3600.0,  # daily
        'kwargs': {'backup_type': 'aws'},
    },
}



