# Generated by Django 6.0 on 2026-07-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_chatmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, help_text='e.g. First Term Mathematics Exam for JSS1'),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], default='first', max_length=10),
        ),
    ]
